crawler:
    build: ./crawler
    volumes:
        - ./crawler/:/src/
    links:
        - elasticsearch
        - redis
robots:
    build: ./robots
    volumes:
        - ./robots/:/src/
    links:
        - elasticsearch

redis:
    image: redis
    ports:
        - "6379"

elasticsearch:
    image: elasticsearch
    ports:
        - "9200"
        - "9300"
