crawler:
    build: ./crawler
    volumes:
        - ./crawler/:/src/
    links:
        - elasticsearch
        - rabbitmq

fetcher:
    build: ./fetcher
    volumes:
        - ./fetcher/:/src/
    links:
        - elasticsearch
        - rabbitmq

#robots:
#    build: ./robots
#    volumes:
#        - ./robots/:/src/
#    links:
#        - elasticsearch

rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
        - "5672"
    volumes:
      - ./persistence/rabbitmq/:/var/lib/rabbitmq/

elasticsearch:
    build: ./elasticsearch
    ports:
        - "9200:9200"
        - "9300"
    volumes:
      - ./persistence/elasticsearch/:/usr/share/elasticsearch/data/
